// ⚠️  GENERATED FILE - DO NOT EDIT
// This file is automatically generated by 'prisma contract emit'.
// To regenerate, run: prisma contract emit
import type { CodecTypes as MongoCodecTypes, Vector } from '@prisma/orm-mongo/adapter/codec-types';

import type {
  MongoCollection,
  MongoContractWithTypeMaps,
  MongoTypeMaps,
  RelationKeys,
} from '@prisma/orm-mongo/family-contract';
import type {
  Contract as ContractType,
  ExecutionHashBase,
  NamespaceId,
  ProfileHashBase,
  StorageHashBase,
} from '@prisma/orm-mongo/contract/types';

export type StorageHash =
  StorageHashBase<'4d92e6d9da6bc2d0e72d67d40ede9606b424278e7e684386988d068cc38710b7'>;
export type ExecutionHash = ExecutionHashBase<string>;
export type ProfileHash =
  ProfileHashBase<'251b3ce23f6c9f561892e7c1af9d2cc941a13d64ba1aa7226b90036b09568cc3'>;

export type CodecTypes = MongoCodecTypes;

export type FieldOutputTypes = {
  readonly __unbound__: {
    readonly BriefSource: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly url: CodecTypes['mongo/string@1']['output'];
    };
    readonly Flashcard: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly stableKey: CodecTypes['mongo/string@1']['output'];
      readonly front: CodecTypes['mongo/string@1']['output'];
      readonly back: CodecTypes['mongo/string@1']['output'];
      readonly state: 'GENERATED' | 'EDITED' | 'PINNED';
      readonly orderIndex: CodecTypes['mongo/int32@1']['output'];
    };
    readonly FlashcardRequirement: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly flashcardId: CodecTypes['mongo/string@1']['output'];
      readonly requirementId: CodecTypes['mongo/string@1']['output'];
    };
    readonly Kit: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly userId: CodecTypes['mongo/string@1']['output'];
      readonly dedupeHash: CodecTypes['mongo/string@1']['output'] | null;
      readonly companyName: CodecTypes['mongo/string@1']['output'] | null;
      readonly companyUrl: CodecTypes['mongo/string@1']['output'];
      readonly jdText: CodecTypes['mongo/string@1']['output'];
      readonly jdChars: CodecTypes['mongo/int32@1']['output'] | null;
      readonly role: CodecTypes['mongo/string@1']['output'] | null;
      readonly location: CodecTypes['mongo/string@1']['output'] | null;
      readonly daysAvailable: CodecTypes['mongo/int32@1']['output'];
      readonly researchedAt: CodecTypes['mongo/date@1']['output'] | null;
      readonly briefSummary: CodecTypes['mongo/string@1']['output'] | null;
      readonly briefWhatTheyDo: CodecTypes['mongo/string@1']['output'] | null;
      readonly briefState: 'GENERATED' | 'EDITED' | 'PINNED' | null;
      readonly roleTitle: CodecTypes['mongo/string@1']['output'] | null;
      readonly roleSeniority: CodecTypes['mongo/string@1']['output'] | null;
      readonly research: CodecTypes['mongo/string@1']['output'] | null;
      readonly scheduleStale: CodecTypes['mongo/bool@1']['output'] | null;
      readonly status:
        | 'PENDING'
        | 'RUNNING'
        | 'DRAFT'
        | 'RESEARCHING'
        | 'EXTRACTING'
        | 'GENERATING'
        | 'CHECKING_COVERAGE'
        | 'SCHEDULING'
        | 'READY'
        | 'FAILED';
      readonly failureReason: CodecTypes['mongo/string@1']['output'] | null;
      readonly errorMessage: CodecTypes['mongo/string@1']['output'] | null;
      readonly result: CodecTypes['mongo/string@1']['output'] | null;
      readonly coveragePasses: CodecTypes['mongo/int32@1']['output'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
      readonly updatedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly KitPage: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly url: CodecTypes['mongo/string@1']['output'];
    };
    readonly PracticeAttempt: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly sessionId: CodecTypes['mongo/string@1']['output'];
      readonly flashcardId: CodecTypes['mongo/string@1']['output'];
      readonly confidence: CodecTypes['mongo/int32@1']['output'] | null;
      readonly skipped: CodecTypes['mongo/bool@1']['output'] | null;
      readonly attemptedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly PracticeSession: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly userId: CodecTypes['mongo/string@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly startedAt: CodecTypes['mongo/date@1']['output'];
      readonly endedAt: CodecTypes['mongo/date@1']['output'] | null;
    };
    readonly Question: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly stableKey: CodecTypes['mongo/string@1']['output'];
      readonly category: CodecTypes['mongo/string@1']['output'];
      readonly prompt: CodecTypes['mongo/string@1']['output'];
      readonly answerOutline: CodecTypes['mongo/string@1']['output'];
      readonly difficulty: CodecTypes['mongo/int32@1']['output'];
      readonly state: 'GENERATED' | 'EDITED' | 'PINNED';
      readonly orderIndex: CodecTypes['mongo/int32@1']['output'];
    };
    readonly QuestionRequirement: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly questionId: CodecTypes['mongo/string@1']['output'];
      readonly requirementId: CodecTypes['mongo/string@1']['output'];
    };
    readonly Requirement: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly stableKey: CodecTypes['mongo/string@1']['output'];
      readonly text: CodecTypes['mongo/string@1']['output'];
      readonly kind: CodecTypes['mongo/string@1']['output'];
      readonly priority: CodecTypes['mongo/string@1']['output'];
    };
    readonly Responsibility: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly description: CodecTypes['mongo/string@1']['output'];
    };
    readonly ScheduleDay: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly dayNumber: CodecTypes['mongo/int32@1']['output'];
      readonly focus: CodecTypes['mongo/string@1']['output'];
      readonly minutes: CodecTypes['mongo/int32@1']['output'];
    };
    readonly ScheduleDayQuestion: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly scheduleDayId: CodecTypes['mongo/string@1']['output'];
      readonly questionId: CodecTypes['mongo/string@1']['output'];
      readonly position: CodecTypes['mongo/int32@1']['output'];
    };
    readonly SourcePage: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly url: CodecTypes['mongo/string@1']['output'];
      readonly kind: CodecTypes['mongo/string@1']['output'];
      readonly status: CodecTypes['mongo/string@1']['output'];
      readonly reason: CodecTypes['mongo/string@1']['output'] | null;
      readonly fetchedAt: CodecTypes['mongo/date@1']['output'];
    };
    readonly UncoveredRequirement: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly kitId: CodecTypes['mongo/string@1']['output'];
      readonly stableKey: CodecTypes['mongo/string@1']['output'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['output'];
      readonly name: CodecTypes['mongo/string@1']['output'];
      readonly email: CodecTypes['mongo/string@1']['output'];
      readonly passwordHash: CodecTypes['mongo/string@1']['output'];
      readonly createdAt: CodecTypes['mongo/date@1']['output'];
    };
  };
};
export type FieldInputTypes = {
  readonly __unbound__: {
    readonly BriefSource: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly url: CodecTypes['mongo/string@1']['input'];
    };
    readonly Flashcard: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly stableKey: CodecTypes['mongo/string@1']['input'];
      readonly front: CodecTypes['mongo/string@1']['input'];
      readonly back: CodecTypes['mongo/string@1']['input'];
      readonly state: 'GENERATED' | 'EDITED' | 'PINNED';
      readonly orderIndex: CodecTypes['mongo/int32@1']['input'];
    };
    readonly FlashcardRequirement: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly flashcardId: CodecTypes['mongo/string@1']['input'];
      readonly requirementId: CodecTypes['mongo/string@1']['input'];
    };
    readonly Kit: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly userId: CodecTypes['mongo/string@1']['input'];
      readonly dedupeHash: CodecTypes['mongo/string@1']['input'] | null;
      readonly companyName: CodecTypes['mongo/string@1']['input'] | null;
      readonly companyUrl: CodecTypes['mongo/string@1']['input'];
      readonly jdText: CodecTypes['mongo/string@1']['input'];
      readonly jdChars: CodecTypes['mongo/int32@1']['input'] | null;
      readonly role: CodecTypes['mongo/string@1']['input'] | null;
      readonly location: CodecTypes['mongo/string@1']['input'] | null;
      readonly daysAvailable: CodecTypes['mongo/int32@1']['input'];
      readonly researchedAt: CodecTypes['mongo/date@1']['input'] | null;
      readonly briefSummary: CodecTypes['mongo/string@1']['input'] | null;
      readonly briefWhatTheyDo: CodecTypes['mongo/string@1']['input'] | null;
      readonly briefState: 'GENERATED' | 'EDITED' | 'PINNED' | null;
      readonly roleTitle: CodecTypes['mongo/string@1']['input'] | null;
      readonly roleSeniority: CodecTypes['mongo/string@1']['input'] | null;
      readonly research: CodecTypes['mongo/string@1']['input'] | null;
      readonly scheduleStale: CodecTypes['mongo/bool@1']['input'] | null;
      readonly status:
        | 'PENDING'
        | 'RUNNING'
        | 'DRAFT'
        | 'RESEARCHING'
        | 'EXTRACTING'
        | 'GENERATING'
        | 'CHECKING_COVERAGE'
        | 'SCHEDULING'
        | 'READY'
        | 'FAILED';
      readonly failureReason: CodecTypes['mongo/string@1']['input'] | null;
      readonly errorMessage: CodecTypes['mongo/string@1']['input'] | null;
      readonly result: CodecTypes['mongo/string@1']['input'] | null;
      readonly coveragePasses: CodecTypes['mongo/int32@1']['input'] | null;
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
      readonly updatedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly KitPage: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly url: CodecTypes['mongo/string@1']['input'];
    };
    readonly PracticeAttempt: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly sessionId: CodecTypes['mongo/string@1']['input'];
      readonly flashcardId: CodecTypes['mongo/string@1']['input'];
      readonly confidence: CodecTypes['mongo/int32@1']['input'] | null;
      readonly skipped: CodecTypes['mongo/bool@1']['input'] | null;
      readonly attemptedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly PracticeSession: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly userId: CodecTypes['mongo/string@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly startedAt: CodecTypes['mongo/date@1']['input'];
      readonly endedAt: CodecTypes['mongo/date@1']['input'] | null;
    };
    readonly Question: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly stableKey: CodecTypes['mongo/string@1']['input'];
      readonly category: CodecTypes['mongo/string@1']['input'];
      readonly prompt: CodecTypes['mongo/string@1']['input'];
      readonly answerOutline: CodecTypes['mongo/string@1']['input'];
      readonly difficulty: CodecTypes['mongo/int32@1']['input'];
      readonly state: 'GENERATED' | 'EDITED' | 'PINNED';
      readonly orderIndex: CodecTypes['mongo/int32@1']['input'];
    };
    readonly QuestionRequirement: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly questionId: CodecTypes['mongo/string@1']['input'];
      readonly requirementId: CodecTypes['mongo/string@1']['input'];
    };
    readonly Requirement: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly stableKey: CodecTypes['mongo/string@1']['input'];
      readonly text: CodecTypes['mongo/string@1']['input'];
      readonly kind: CodecTypes['mongo/string@1']['input'];
      readonly priority: CodecTypes['mongo/string@1']['input'];
    };
    readonly Responsibility: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly description: CodecTypes['mongo/string@1']['input'];
    };
    readonly ScheduleDay: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly dayNumber: CodecTypes['mongo/int32@1']['input'];
      readonly focus: CodecTypes['mongo/string@1']['input'];
      readonly minutes: CodecTypes['mongo/int32@1']['input'];
    };
    readonly ScheduleDayQuestion: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly scheduleDayId: CodecTypes['mongo/string@1']['input'];
      readonly questionId: CodecTypes['mongo/string@1']['input'];
      readonly position: CodecTypes['mongo/int32@1']['input'];
    };
    readonly SourcePage: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly url: CodecTypes['mongo/string@1']['input'];
      readonly kind: CodecTypes['mongo/string@1']['input'];
      readonly status: CodecTypes['mongo/string@1']['input'];
      readonly reason: CodecTypes['mongo/string@1']['input'] | null;
      readonly fetchedAt: CodecTypes['mongo/date@1']['input'];
    };
    readonly UncoveredRequirement: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly kitId: CodecTypes['mongo/string@1']['input'];
      readonly stableKey: CodecTypes['mongo/string@1']['input'];
    };
    readonly User: {
      readonly _id: CodecTypes['mongo/objectId@1']['input'];
      readonly name: CodecTypes['mongo/string@1']['input'];
      readonly email: CodecTypes['mongo/string@1']['input'];
      readonly passwordHash: CodecTypes['mongo/string@1']['input'];
      readonly createdAt: CodecTypes['mongo/date@1']['input'];
    };
  };
};

export namespace Models {
  export type unbound_User = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    name: CodecTypes['mongo/string@1']['output'];
    email: CodecTypes['mongo/string@1']['output'];
    passwordHash: CodecTypes['mongo/string@1']['output'];
    createdAt: CodecTypes['mongo/date@1']['output'];
    kits: unbound_Kit[];
    practiceSessions: unbound_PracticeSession[];
    readonly [RelationKeys]?: 'kits' | 'practiceSessions';
  };
  export type unbound_Kit = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    userId: CodecTypes['mongo/string@1']['output'];
    dedupeHash: CodecTypes['mongo/string@1']['output'] | null;
    companyName: CodecTypes['mongo/string@1']['output'] | null;
    companyUrl: CodecTypes['mongo/string@1']['output'];
    jdText: CodecTypes['mongo/string@1']['output'];
    jdChars: CodecTypes['mongo/int32@1']['output'] | null;
    role: CodecTypes['mongo/string@1']['output'] | null;
    location: CodecTypes['mongo/string@1']['output'] | null;
    daysAvailable: CodecTypes['mongo/int32@1']['output'];
    researchedAt: CodecTypes['mongo/date@1']['output'] | null;
    briefSummary: CodecTypes['mongo/string@1']['output'] | null;
    briefWhatTheyDo: CodecTypes['mongo/string@1']['output'] | null;
    briefState: 'GENERATED' | 'EDITED' | 'PINNED' | null;
    roleTitle: CodecTypes['mongo/string@1']['output'] | null;
    roleSeniority: CodecTypes['mongo/string@1']['output'] | null;
    research: CodecTypes['mongo/string@1']['output'] | null;
    scheduleStale: CodecTypes['mongo/bool@1']['output'] | null;
    status:
      | 'PENDING'
      | 'RUNNING'
      | 'DRAFT'
      | 'RESEARCHING'
      | 'EXTRACTING'
      | 'GENERATING'
      | 'CHECKING_COVERAGE'
      | 'SCHEDULING'
      | 'READY'
      | 'FAILED';
    failureReason: CodecTypes['mongo/string@1']['output'] | null;
    errorMessage: CodecTypes['mongo/string@1']['output'] | null;
    result: CodecTypes['mongo/string@1']['output'] | null;
    coveragePasses: CodecTypes['mongo/int32@1']['output'] | null;
    createdAt: CodecTypes['mongo/date@1']['output'];
    updatedAt: CodecTypes['mongo/date@1']['output'];
    user: unbound_User;
    pagesUsed: unbound_KitPage[];
    briefSources: unbound_BriefSource[];
    responsibilities: unbound_Responsibility[];
    uncoveredRequirements: unbound_UncoveredRequirement[];
    sourcePages: unbound_SourcePage[];
    requirements: unbound_Requirement[];
    questions: unbound_Question[];
    flashcards: unbound_Flashcard[];
    scheduleDays: unbound_ScheduleDay[];
    practiceSessions: unbound_PracticeSession[];
    readonly [RelationKeys]?:
      | 'user'
      | 'pagesUsed'
      | 'briefSources'
      | 'responsibilities'
      | 'uncoveredRequirements'
      | 'sourcePages'
      | 'requirements'
      | 'questions'
      | 'flashcards'
      | 'scheduleDays'
      | 'practiceSessions';
  };
  export type unbound_KitPage = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    url: CodecTypes['mongo/string@1']['output'];
    kit: unbound_Kit;
    readonly [RelationKeys]?: 'kit';
  };
  export type unbound_BriefSource = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    url: CodecTypes['mongo/string@1']['output'];
    kit: unbound_Kit;
    readonly [RelationKeys]?: 'kit';
  };
  export type unbound_Responsibility = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    description: CodecTypes['mongo/string@1']['output'];
    kit: unbound_Kit;
    readonly [RelationKeys]?: 'kit';
  };
  export type unbound_UncoveredRequirement = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    stableKey: CodecTypes['mongo/string@1']['output'];
    kit: unbound_Kit;
    readonly [RelationKeys]?: 'kit';
  };
  export type unbound_SourcePage = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    url: CodecTypes['mongo/string@1']['output'];
    kind: CodecTypes['mongo/string@1']['output'];
    status: CodecTypes['mongo/string@1']['output'];
    reason: CodecTypes['mongo/string@1']['output'] | null;
    fetchedAt: CodecTypes['mongo/date@1']['output'];
    kit: unbound_Kit;
    readonly [RelationKeys]?: 'kit';
  };
  export type unbound_Requirement = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    stableKey: CodecTypes['mongo/string@1']['output'];
    text: CodecTypes['mongo/string@1']['output'];
    kind: CodecTypes['mongo/string@1']['output'];
    priority: CodecTypes['mongo/string@1']['output'];
    kit: unbound_Kit;
    questions: unbound_QuestionRequirement[];
    flashcards: unbound_FlashcardRequirement[];
    readonly [RelationKeys]?: 'kit' | 'questions' | 'flashcards';
  };
  export type unbound_Question = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    stableKey: CodecTypes['mongo/string@1']['output'];
    category: CodecTypes['mongo/string@1']['output'];
    prompt: CodecTypes['mongo/string@1']['output'];
    answerOutline: CodecTypes['mongo/string@1']['output'];
    difficulty: CodecTypes['mongo/int32@1']['output'];
    state: 'GENERATED' | 'EDITED' | 'PINNED';
    orderIndex: CodecTypes['mongo/int32@1']['output'];
    kit: unbound_Kit;
    requirements: unbound_QuestionRequirement[];
    scheduleSlots: unbound_ScheduleDayQuestion[];
    readonly [RelationKeys]?: 'kit' | 'requirements' | 'scheduleSlots';
  };
  export type unbound_QuestionRequirement = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    questionId: CodecTypes['mongo/string@1']['output'];
    requirementId: CodecTypes['mongo/string@1']['output'];
    question: unbound_Question;
    requirement: unbound_Requirement;
    readonly [RelationKeys]?: 'question' | 'requirement';
  };
  export type unbound_Flashcard = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    stableKey: CodecTypes['mongo/string@1']['output'];
    front: CodecTypes['mongo/string@1']['output'];
    back: CodecTypes['mongo/string@1']['output'];
    state: 'GENERATED' | 'EDITED' | 'PINNED';
    orderIndex: CodecTypes['mongo/int32@1']['output'];
    kit: unbound_Kit;
    requirements: unbound_FlashcardRequirement[];
    attempts: unbound_PracticeAttempt[];
    readonly [RelationKeys]?: 'kit' | 'requirements' | 'attempts';
  };
  export type unbound_FlashcardRequirement = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    flashcardId: CodecTypes['mongo/string@1']['output'];
    requirementId: CodecTypes['mongo/string@1']['output'];
    flashcard: unbound_Flashcard;
    requirement: unbound_Requirement;
    readonly [RelationKeys]?: 'flashcard' | 'requirement';
  };
  export type unbound_ScheduleDay = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    dayNumber: CodecTypes['mongo/int32@1']['output'];
    focus: CodecTypes['mongo/string@1']['output'];
    minutes: CodecTypes['mongo/int32@1']['output'];
    kit: unbound_Kit;
    questions: unbound_ScheduleDayQuestion[];
    readonly [RelationKeys]?: 'kit' | 'questions';
  };
  export type unbound_ScheduleDayQuestion = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    scheduleDayId: CodecTypes['mongo/string@1']['output'];
    questionId: CodecTypes['mongo/string@1']['output'];
    position: CodecTypes['mongo/int32@1']['output'];
    scheduleDay: unbound_ScheduleDay;
    question: unbound_Question;
    readonly [RelationKeys]?: 'scheduleDay' | 'question';
  };
  export type unbound_PracticeSession = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    userId: CodecTypes['mongo/string@1']['output'];
    kitId: CodecTypes['mongo/string@1']['output'];
    startedAt: CodecTypes['mongo/date@1']['output'];
    endedAt: CodecTypes['mongo/date@1']['output'] | null;
    user: unbound_User;
    kit: unbound_Kit;
    attempts: unbound_PracticeAttempt[];
    readonly [RelationKeys]?: 'user' | 'kit' | 'attempts';
  };
  export type unbound_PracticeAttempt = {
    _id: CodecTypes['mongo/objectId@1']['output'];
    sessionId: CodecTypes['mongo/string@1']['output'];
    flashcardId: CodecTypes['mongo/string@1']['output'];
    confidence: CodecTypes['mongo/int32@1']['output'] | null;
    skipped: CodecTypes['mongo/bool@1']['output'] | null;
    attemptedAt: CodecTypes['mongo/date@1']['output'];
    session: unbound_PracticeSession;
    flashcard: unbound_Flashcard;
    readonly [RelationKeys]?: 'session' | 'flashcard';
  };
}

export declare const models: {
  __unbound__: {
    User: Models.unbound_User;
    Kit: Models.unbound_Kit;
    KitPage: Models.unbound_KitPage;
    BriefSource: Models.unbound_BriefSource;
    Responsibility: Models.unbound_Responsibility;
    UncoveredRequirement: Models.unbound_UncoveredRequirement;
    SourcePage: Models.unbound_SourcePage;
    Requirement: Models.unbound_Requirement;
    Question: Models.unbound_Question;
    QuestionRequirement: Models.unbound_QuestionRequirement;
    Flashcard: Models.unbound_Flashcard;
    FlashcardRequirement: Models.unbound_FlashcardRequirement;
    ScheduleDay: Models.unbound_ScheduleDay;
    ScheduleDayQuestion: Models.unbound_ScheduleDayQuestion;
    PracticeSession: Models.unbound_PracticeSession;
    PracticeAttempt: Models.unbound_PracticeAttempt;
  };
};

export type TypeMaps = MongoTypeMaps<CodecTypes, FieldOutputTypes, FieldInputTypes>;

type ContractBase = Omit<
  ContractType<{
    readonly namespaces: {
      readonly __unbound__: {
        readonly id: '__unbound__';
        readonly kind: 'mongo-database';
        readonly entries: {
          readonly collection: {
            readonly briefSource: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly url: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'kitId', 'url'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly flashcard: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly stableKey: { readonly bsonType: 'string' };
                    readonly front: { readonly bsonType: 'string' };
                    readonly back: { readonly bsonType: 'string' };
                    readonly state: {
                      readonly bsonType: 'string';
                      readonly enum: readonly ['GENERATED', 'EDITED', 'PINNED'];
                    };
                    readonly orderIndex: { readonly bsonType: 'int' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'back',
                    'front',
                    'kitId',
                    'orderIndex',
                    'stableKey',
                    'state',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly flashcardRequirement: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'flashcardId'; readonly direction: 1 },
                    { readonly field: 'requirementId'; readonly direction: 1 },
                  ];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly flashcardId: { readonly bsonType: 'string' };
                    readonly requirementId: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'flashcardId', 'requirementId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly kit: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'userId'; readonly direction: 1 }];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'dedupeHash'; readonly direction: 1 }];
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly userId: { readonly bsonType: 'string' };
                    readonly dedupeHash: { readonly bsonType: readonly ['null', 'string'] };
                    readonly companyName: { readonly bsonType: readonly ['null', 'string'] };
                    readonly companyUrl: { readonly bsonType: 'string' };
                    readonly jdText: { readonly bsonType: 'string' };
                    readonly jdChars: { readonly bsonType: readonly ['null', 'int'] };
                    readonly role: { readonly bsonType: readonly ['null', 'string'] };
                    readonly location: { readonly bsonType: readonly ['null', 'string'] };
                    readonly daysAvailable: { readonly bsonType: 'int' };
                    readonly researchedAt: { readonly bsonType: readonly ['null', 'date'] };
                    readonly briefSummary: { readonly bsonType: readonly ['null', 'string'] };
                    readonly briefWhatTheyDo: { readonly bsonType: readonly ['null', 'string'] };
                    readonly briefState: {
                      readonly bsonType: readonly ['null', 'string'];
                      readonly enum: readonly ['GENERATED', 'EDITED', 'PINNED', null];
                    };
                    readonly roleTitle: { readonly bsonType: readonly ['null', 'string'] };
                    readonly roleSeniority: { readonly bsonType: readonly ['null', 'string'] };
                    readonly research: { readonly bsonType: readonly ['null', 'string'] };
                    readonly scheduleStale: { readonly bsonType: readonly ['null', 'bool'] };
                    readonly status: {
                      readonly bsonType: 'string';
                      readonly enum: readonly [
                        'PENDING',
                        'RUNNING',
                        'DRAFT',
                        'RESEARCHING',
                        'EXTRACTING',
                        'GENERATING',
                        'CHECKING_COVERAGE',
                        'SCHEDULING',
                        'READY',
                        'FAILED',
                      ];
                    };
                    readonly failureReason: { readonly bsonType: readonly ['null', 'string'] };
                    readonly errorMessage: { readonly bsonType: readonly ['null', 'string'] };
                    readonly result: { readonly bsonType: readonly ['null', 'string'] };
                    readonly coveragePasses: { readonly bsonType: readonly ['null', 'int'] };
                    readonly createdAt: { readonly bsonType: 'date' };
                    readonly updatedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'companyUrl',
                    'createdAt',
                    'daysAvailable',
                    'jdText',
                    'status',
                    'updatedAt',
                    'userId',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly kitPage: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly url: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'kitId', 'url'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly practiceAttempt: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'sessionId'; readonly direction: 1 }];
                },
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'flashcardId'; readonly direction: 1 },
                  ];
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly sessionId: { readonly bsonType: 'string' };
                    readonly flashcardId: { readonly bsonType: 'string' };
                    readonly confidence: { readonly bsonType: readonly ['null', 'int'] };
                    readonly skipped: { readonly bsonType: readonly ['null', 'bool'] };
                    readonly attemptedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'attemptedAt', 'flashcardId', 'sessionId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly practiceSession: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'userId'; readonly direction: 1 },
                    { readonly field: 'kitId'; readonly direction: 1 },
                  ];
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly userId: { readonly bsonType: 'string' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly startedAt: { readonly bsonType: 'date' };
                    readonly endedAt: { readonly bsonType: readonly ['null', 'date'] };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'kitId', 'startedAt', 'userId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly question: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'kitId'; readonly direction: 1 },
                    { readonly field: 'stableKey'; readonly direction: 1 },
                  ];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly stableKey: { readonly bsonType: 'string' };
                    readonly category: { readonly bsonType: 'string' };
                    readonly prompt: { readonly bsonType: 'string' };
                    readonly answerOutline: { readonly bsonType: 'string' };
                    readonly difficulty: { readonly bsonType: 'int' };
                    readonly state: {
                      readonly bsonType: 'string';
                      readonly enum: readonly ['GENERATED', 'EDITED', 'PINNED'];
                    };
                    readonly orderIndex: { readonly bsonType: 'int' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'answerOutline',
                    'category',
                    'difficulty',
                    'kitId',
                    'orderIndex',
                    'prompt',
                    'stableKey',
                    'state',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly questionRequirement: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'questionId'; readonly direction: 1 },
                    { readonly field: 'requirementId'; readonly direction: 1 },
                  ];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly questionId: { readonly bsonType: 'string' };
                    readonly requirementId: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'questionId', 'requirementId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly requirement: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'kitId'; readonly direction: 1 },
                    { readonly field: 'stableKey'; readonly direction: 1 },
                  ];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly stableKey: { readonly bsonType: 'string' };
                    readonly text: { readonly bsonType: 'string' };
                    readonly kind: { readonly bsonType: 'string' };
                    readonly priority: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'kind',
                    'kitId',
                    'priority',
                    'stableKey',
                    'text',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly responsibility: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly description: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'description', 'kitId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly scheduleDay: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'kitId'; readonly direction: 1 },
                    { readonly field: 'dayNumber'; readonly direction: 1 },
                  ];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly dayNumber: { readonly bsonType: 'int' };
                    readonly focus: { readonly bsonType: 'string' };
                    readonly minutes: { readonly bsonType: 'int' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'dayNumber', 'focus', 'kitId', 'minutes'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly scheduleDayQuestion: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [
                    { readonly field: 'scheduleDayId'; readonly direction: 1 },
                    { readonly field: 'questionId'; readonly direction: 1 },
                  ];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly scheduleDayId: { readonly bsonType: 'string' };
                    readonly questionId: { readonly bsonType: 'string' };
                    readonly position: { readonly bsonType: 'int' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'position', 'questionId', 'scheduleDayId'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly sourcePage: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly url: { readonly bsonType: 'string' };
                    readonly kind: { readonly bsonType: 'string' };
                    readonly status: { readonly bsonType: 'string' };
                    readonly reason: { readonly bsonType: readonly ['null', 'string'] };
                    readonly fetchedAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly [
                    '_id',
                    'fetchedAt',
                    'kind',
                    'kitId',
                    'status',
                    'url',
                  ];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly uncoveredRequirement: {
              readonly kind: 'mongo-collection';
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly kitId: { readonly bsonType: 'string' };
                    readonly stableKey: { readonly bsonType: 'string' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'kitId', 'stableKey'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
            readonly user: {
              readonly kind: 'mongo-collection';
              readonly indexes: readonly [
                {
                  readonly kind: 'mongo-index';
                  readonly keys: readonly [{ readonly field: 'email'; readonly direction: 1 }];
                  readonly unique: true;
                },
              ];
              readonly validator: {
                readonly kind: 'mongo-validator';
                readonly jsonSchema: {
                  readonly bsonType: 'object';
                  readonly properties: {
                    readonly _id: { readonly bsonType: 'objectId' };
                    readonly name: { readonly bsonType: 'string' };
                    readonly email: { readonly bsonType: 'string' };
                    readonly passwordHash: { readonly bsonType: 'string' };
                    readonly createdAt: { readonly bsonType: 'date' };
                  };
                  readonly additionalProperties: false;
                  readonly required: readonly ['_id', 'createdAt', 'email', 'name', 'passwordHash'];
                };
                readonly validationLevel: 'strict';
                readonly validationAction: 'error';
              };
            };
          };
        };
      };
    };
    readonly storageHash: StorageHash;
  }>,
  'roots' | 'domain'
> & {
  readonly target: 'mongo';
  readonly targetFamily: 'mongo';
  readonly roots: {
    readonly user: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'User' };
    readonly kit: { readonly namespace: '__unbound__' & NamespaceId; readonly model: 'Kit' };
    readonly kitPage: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'KitPage';
    };
    readonly briefSource: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'BriefSource';
    };
    readonly responsibility: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Responsibility';
    };
    readonly uncoveredRequirement: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'UncoveredRequirement';
    };
    readonly sourcePage: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'SourcePage';
    };
    readonly requirement: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Requirement';
    };
    readonly question: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Question';
    };
    readonly questionRequirement: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'QuestionRequirement';
    };
    readonly flashcard: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'Flashcard';
    };
    readonly flashcardRequirement: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'FlashcardRequirement';
    };
    readonly scheduleDay: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'ScheduleDay';
    };
    readonly scheduleDayQuestion: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'ScheduleDayQuestion';
    };
    readonly practiceSession: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'PracticeSession';
    };
    readonly practiceAttempt: {
      readonly namespace: '__unbound__' & NamespaceId;
      readonly model: 'PracticeAttempt';
    };
  };
  readonly domain: {
    readonly namespaces: {
      readonly __unbound__: {
        readonly models: {
          readonly BriefSource: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly url: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'briefSource' };
          };
          readonly Flashcard: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly stableKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly front: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly back: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly state: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly orderIndex: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
            readonly relations: {
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly requirements: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'FlashcardRequirement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['flashcardId'];
                };
              };
              readonly attempts: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'PracticeAttempt';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['flashcardId'];
                };
              };
            };
            readonly storage: { readonly collection: 'flashcard' };
          };
          readonly FlashcardRequirement: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly flashcardId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly requirementId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly flashcard: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Flashcard';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['flashcardId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly requirement: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Requirement';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['requirementId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'flashcardRequirement' };
          };
          readonly Kit: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly dedupeHash: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly companyName: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly companyUrl: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly jdText: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly jdChars: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly role: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly location: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly daysAvailable: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly researchedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly briefSummary: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly briefWhatTheyDo: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly briefState: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly roleTitle: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly roleSeniority: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly research: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly scheduleStale: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly failureReason: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly errorMessage: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly result: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly coveragePasses: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly updatedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly pagesUsed: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'KitPage';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
              readonly briefSources: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'BriefSource';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
              readonly responsibilities: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Responsibility';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
              readonly uncoveredRequirements: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'UncoveredRequirement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
              readonly sourcePages: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'SourcePage';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
              readonly requirements: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Requirement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
              readonly questions: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Question';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
              readonly flashcards: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Flashcard';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
              readonly scheduleDays: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'ScheduleDay';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
              readonly practiceSessions: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'PracticeSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['kitId'];
                };
              };
            };
            readonly storage: { readonly collection: 'kit' };
          };
          readonly KitPage: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly url: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'kitPage' };
          };
          readonly PracticeAttempt: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly sessionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly flashcardId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly confidence: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly skipped: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/bool@1' };
              };
              readonly attemptedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly session: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'PracticeSession';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['sessionId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly flashcard: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Flashcard';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['flashcardId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'practiceAttempt' };
          };
          readonly PracticeSession: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly userId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly startedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
              readonly endedAt: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly user: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'User';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['userId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly attempts: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'PracticeAttempt';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['sessionId'];
                };
              };
            };
            readonly storage: { readonly collection: 'practiceSession' };
          };
          readonly Question: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly stableKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly category: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly prompt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly answerOutline: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly difficulty: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly state: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly orderIndex: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
            readonly relations: {
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly requirements: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'QuestionRequirement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['questionId'];
                };
              };
              readonly scheduleSlots: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'ScheduleDayQuestion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['questionId'];
                };
              };
            };
            readonly storage: { readonly collection: 'question' };
          };
          readonly QuestionRequirement: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly questionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly requirementId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly question: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Question';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['questionId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly requirement: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Requirement';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['requirementId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'questionRequirement' };
          };
          readonly Requirement: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly stableKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly text: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly priority: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly questions: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'QuestionRequirement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['requirementId'];
                };
              };
              readonly flashcards: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'FlashcardRequirement';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['requirementId'];
                };
              };
            };
            readonly storage: { readonly collection: 'requirement' };
          };
          readonly Responsibility: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly description: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'responsibility' };
          };
          readonly ScheduleDay: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly dayNumber: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
              readonly focus: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly minutes: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
            readonly relations: {
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly questions: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'ScheduleDayQuestion';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['scheduleDayId'];
                };
              };
            };
            readonly storage: { readonly collection: 'scheduleDay' };
          };
          readonly ScheduleDayQuestion: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly scheduleDayId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly questionId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly position: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/int32@1' };
              };
            };
            readonly relations: {
              readonly scheduleDay: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'ScheduleDay';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['scheduleDayId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
              readonly question: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Question';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['questionId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'scheduleDayQuestion' };
          };
          readonly SourcePage: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly url: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly kind: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly status: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly reason: {
                readonly nullable: true;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly fetchedAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'sourcePage' };
          };
          readonly UncoveredRequirement: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly kitId: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly stableKey: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
            };
            readonly relations: {
              readonly kit: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: 'N:1';
                readonly nullable: false;
                readonly on: {
                  readonly localFields: readonly ['kitId'];
                  readonly targetFields: readonly ['_id'];
                };
              };
            };
            readonly storage: { readonly collection: 'uncoveredRequirement' };
          };
          readonly User: {
            readonly fields: {
              readonly _id: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/objectId@1' };
              };
              readonly name: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly email: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly passwordHash: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/string@1' };
              };
              readonly createdAt: {
                readonly nullable: false;
                readonly type: { readonly kind: 'scalar'; readonly codecId: 'mongo/date@1' };
              };
            };
            readonly relations: {
              readonly kits: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'Kit';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
              readonly practiceSessions: {
                readonly to: {
                  readonly namespace: '__unbound__' & NamespaceId;
                  readonly model: 'PracticeSession';
                };
                readonly cardinality: '1:N';
                readonly on: {
                  readonly localFields: readonly ['_id'];
                  readonly targetFields: readonly ['userId'];
                };
              };
            };
            readonly storage: { readonly collection: 'user' };
          };
        };
        readonly enum: {
          readonly KitStatus: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'PENDING'; readonly value: 'PENDING' },
              { readonly name: 'RUNNING'; readonly value: 'RUNNING' },
              { readonly name: 'DRAFT'; readonly value: 'DRAFT' },
              { readonly name: 'RESEARCHING'; readonly value: 'RESEARCHING' },
              { readonly name: 'EXTRACTING'; readonly value: 'EXTRACTING' },
              { readonly name: 'GENERATING'; readonly value: 'GENERATING' },
              { readonly name: 'CHECKING_COVERAGE'; readonly value: 'CHECKING_COVERAGE' },
              { readonly name: 'SCHEDULING'; readonly value: 'SCHEDULING' },
              { readonly name: 'READY'; readonly value: 'READY' },
              { readonly name: 'FAILED'; readonly value: 'FAILED' },
            ];
          };
          readonly ItemState: {
            readonly codecId: 'mongo/string@1';
            readonly members: readonly [
              { readonly name: 'GENERATED'; readonly value: 'GENERATED' },
              { readonly name: 'EDITED'; readonly value: 'EDITED' },
              { readonly name: 'PINNED'; readonly value: 'PINNED' },
            ];
          };
        };
      };
    };
  };
  readonly capabilities: {};
  readonly extensions: {};
  readonly meta: {};

  readonly profileHash: ProfileHash;
};

export type Contract = MongoContractWithTypeMaps<ContractBase, TypeMaps>;
